version: "3.7"
services:

  stepfunctions-offline:
    build: .
    env_file:
      - ./.env.offline
    depends_on:
      - stepfunctions-cli
    network_mode: "host"

  stepfunctions-cli:
    image: amazon/aws-stepfunctions-local
    env_file:
      - ./.env.offline
    ports:
      - "8083:8083"
    network_mode: "host"
